# This is a basic workflow to help you get started with Actions

name: Discord Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout tag
        uses: actions/checkout@v3
      # Runs a single command to fail
      - name: Force failure
        run: exit 1
      # Test discord notification
      - uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          nodetails: true
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: Release iOS to TestFlight
          description: 'Click [here](https://github.com/cardstack/cardwallet/actions/runs/`${{github.run_id}}`) to review the issue'
          color: 0xff91a4
